version: 0.2

env:
  variables:
    CODE_SRC_DIR: python-rest-terraform/application/
    SCRIPT_DIR: ./python-rest-terraform/templates/scripts
    TF_VERSION: "1.9.4"
    ENVIRONMENT: "dev"
    SKIPVALIDATIONFAILURE: "Y"
    ENABLE_UNIT_TEST: "Y"
    ENABLE_TFVALIDATE: "Y"
    ENABLE_TFFORMAT: "Y"
    ENABLE_TFCHECKOV: "Y"
    ENABLE_TFSEC: "Y"
    TFSEC_VERSION: "v1.28.10"

phases:
  install:
    runtime-versions:
      python: 3.12
      golang: 1.22
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /bin
      - rm terraform.zip
      - yum update -y
      - yum install -y jq awscli
      - pip3 install checkov
      - yum install -y golang
      - wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64
      - chmod +x ./tfsec
      - mv ./tfsec /usr/local/bin/tfsec
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}
      - echo ## VALIDATION : Starting ...
      - mkdir -p ${CODEBUILD_SRC_DIR}/reports
      - /bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/tf_ssp_validation.sh ${SKIPVALIDATIONFAILURE} ${ENABLE_UNIT_TEST} ${ENABLE_TFVALIDATE} ${ENABLE_TFFORMAT} ${ENABLE_TFCHECKOV} ${ENABLE_TFSEC}
      - cp checkov.xml ${CODEBUILD_SRC_DIR}/reports/checkov.xml
      - cp tfsec-junit.xml ${CODEBUILD_SRC_DIR}/reports/tfsec-junit.xml
artifacts:
  files:
    - '**/*'
reports:
  checkov-reports:
    files:
      - ./reports/checkov.xml
    file-format: JUNITXML
  tfsec-reports:
    files:
      - ./reports/tfsec-junit.xml
    file-format: JUNITXML