#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# uninstall-macos.sh — Jamf Pro / macOS MDM uninstall for claude-hub
# Reverses everything done by deploy-macos.sh:
#   1. Removes hub-managed entries from ~/.claude/settings.json (MCP servers, marketplaces)
#   2. Removes hub-* skills from ~/.claude/skills/
#   3. Removes the hub-generated ~/.claude/CLAUDE.md
#   4. Removes the plugin from ~/.claude/plugins/local/claude-hub/
#   5. Removes the SessionStart hook from ~/.claude/settings.json
#   6. Removes the claude-hub data directory (~/.claude/claude-hub/)
#   7. Removes the managed policy files from /Library/Application Support/ClaudeCode/
#
# Must be run as root (sudo). Safe to run multiple times.

set -euo pipefail

LOG_TAG="claude-hub-uninstall"

log() {
    logger -t "$LOG_TAG" "$1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log_error() {
    logger -t "$LOG_TAG" "ERROR: $1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >&2
}

die() {
    log_error "$1"
    exit 1
}

# --- Detect logged-in user (not root) ---
CONSOLE_USER=$(/usr/bin/stat -f "%Su" /dev/console 2>/dev/null || echo "")
if [ -z "$CONSOLE_USER" ] || [ "$CONSOLE_USER" = "root" ]; then
    CONSOLE_USER=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && !/loginwindow/ { print $3 }')
fi
[ -n "$CONSOLE_USER" ] || die "Could not detect logged-in user"

USER_HOME=$(dscl . -read "/Users/$CONSOLE_USER" NFSHomeDirectory | awk '{ print $2 }')
[ -d "$USER_HOME" ] || die "Home directory $USER_HOME does not exist"

log "Uninstalling claude-hub for user=$CONSOLE_USER home=$USER_HOME"

# --- Paths ---
CLAUDE_DIR="$USER_HOME/.claude"
HUB_DIR="$CLAUDE_DIR/claude-hub"
SKILLS_DIR="$CLAUDE_DIR/skills"
PLUGIN_DEST="$CLAUDE_DIR/plugins/local/claude-hub"
USER_SETTINGS="$CLAUDE_DIR/settings.json"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
MANAGED_POLICY_DIR="/Library/Application Support/ClaudeCode"

# --- 1. Remove hub-managed entries from settings.json ---
MANAGED_MCP_FILE="$HUB_DIR/managed_mcp_servers"
MANAGED_MARKETPLACES_FILE="$HUB_DIR/managed_marketplaces"
MANAGED_PLUGINS_FILE="$HUB_DIR/managed_plugins"

if [ -f "$USER_SETTINGS" ] && command -v python3 >/dev/null 2>&1; then
    python3 - "$USER_SETTINGS" "$MANAGED_MCP_FILE" "$MANAGED_MARKETPLACES_FILE" "$MANAGED_PLUGINS_FILE" <<'PYEOF'
import json, sys, os

settings_path, mcp_path, mktp_path, plug_path = sys.argv[1:5]
if not os.path.isfile(settings_path):
    sys.exit(0)
try:
    with open(settings_path) as f:
        settings = json.load(f)
except (json.JSONDecodeError, IOError):
    sys.exit(0)

changed = False
for managed_path, key in [(mcp_path, "mcpServers"), (mktp_path, "extraKnownMarketplaces"), (plug_path, "enabledPlugins")]:
    if not os.path.isfile(managed_path):
        continue
    with open(managed_path) as f:
        managed = set(line.strip() for line in f if line.strip())
    section = settings.get(key, {})
    for name in managed:
        if name in section:
            del section[name]
            changed = True
    if section:
        settings[key] = section
    elif key in settings:
        del settings[key]
        changed = True

if changed:
    with open(settings_path, "w") as f:
        json.dump(settings, f, indent=2)
        f.write("\n")
    print(f"Cleaned hub-managed entries from {settings_path}")
PYEOF
    log "Cleaned hub-managed entries from settings.json"
else
    log "Skipping settings.json cleanup (file missing or no python3)"
fi

# --- 2. Remove hub-* skills ---
if [ -d "$SKILLS_DIR" ]; then
    removed_skills=0
    for skill_dir in "$SKILLS_DIR"/hub-*; do
        [ -e "$skill_dir" ] || continue
        rm -rf "$skill_dir"
        removed_skills=$((removed_skills + 1))
    done
    log "Removed $removed_skills hub-* skill(s) from $SKILLS_DIR"
else
    log "No skills directory found, skipping"
fi

# --- 3. Remove hub-generated CLAUDE.md ---
if [ -f "$CLAUDE_MD" ]; then
    # Only remove if it was generated by claude-hub (check provenance header)
    if head -1 "$CLAUDE_MD" | grep -q "claude-hub" 2>/dev/null; then
        rm -f "$CLAUDE_MD"
        log "Removed hub-generated $CLAUDE_MD"
    else
        log "Skipping $CLAUDE_MD (not generated by claude-hub)"
    fi
else
    log "No $CLAUDE_MD found, skipping"
fi

# --- 4. Remove plugin directory ---
if [ -d "$PLUGIN_DEST" ]; then
    rm -rf "$PLUGIN_DEST"
    log "Removed plugin directory $PLUGIN_DEST"
else
    log "No plugin directory found at $PLUGIN_DEST, skipping"
fi

# --- 5. Remove SessionStart hook from settings.json ---
if [ -f "$USER_SETTINGS" ] && command -v python3 >/dev/null 2>&1; then
    python3 - "$USER_SETTINGS" <<'PYEOF'
import json, sys, os

settings_path = sys.argv[1]
if not os.path.isfile(settings_path):
    sys.exit(0)
try:
    with open(settings_path) as f:
        data = json.load(f)
except (json.JSONDecodeError, IOError):
    sys.exit(0)

changed = False

# Remove enabledPlugins entry (from older deploys)
plugins = data.get("enabledPlugins", {})
if "claude-hub@local" in plugins:
    del plugins["claude-hub@local"]
    data["enabledPlugins"] = plugins
    changed = True

# Remove SessionStart hook entries that reference sync.sh
hooks = data.get("hooks", {})
session_hooks = hooks.get("SessionStart", [])
filtered = []
for entry in session_hooks:
    keep = True
    for h in entry.get("hooks", []):
        if "sync.sh" in h.get("command", ""):
            keep = False
            break
    if keep:
        filtered.append(entry)
if len(filtered) != len(session_hooks):
    if filtered:
        hooks["SessionStart"] = filtered
    else:
        hooks.pop("SessionStart", None)
    data["hooks"] = hooks
    changed = True

if changed:
    with open(settings_path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
PYEOF
    log "Removed SessionStart hook from settings.json"
fi

# --- 6. Remove claude-hub data directory ---
if [ -d "$HUB_DIR" ]; then
    rm -rf "$HUB_DIR"
    log "Removed hub data directory $HUB_DIR"
else
    log "No hub data directory found, skipping"
fi

# --- 7. Remove managed policy files ---
if [ -f "$MANAGED_POLICY_DIR/CLAUDE.md" ]; then
    rm -f "$MANAGED_POLICY_DIR/CLAUDE.md"
    log "Removed managed policy CLAUDE.md"
else
    log "No managed policy CLAUDE.md found, skipping"
fi

if [ -f "$MANAGED_POLICY_DIR/managed-settings.json" ]; then
    rm -f "$MANAGED_POLICY_DIR/managed-settings.json"
    log "Removed managed-settings.json"
else
    log "No managed-settings.json found, skipping"
fi

# Remove the directory if empty
if [ -d "$MANAGED_POLICY_DIR" ]; then
    rmdir "$MANAGED_POLICY_DIR" 2>/dev/null && log "Removed empty $MANAGED_POLICY_DIR" || true
fi

# --- Fix ownership (in case we created anything as root) ---
if [ -d "$CLAUDE_DIR" ]; then
    chown -R "$CONSOLE_USER" "$CLAUDE_DIR"
    log "Fixed ownership of $CLAUDE_DIR"
fi

log "claude-hub uninstall completed successfully"
exit 0
